=== jrybak23/jpa-loading-strategies/src/test/resources/datasets/schema.dtd
<!ELEMENT dataset (
    A*,
    B*,
    C*,
    ITEM*)>

<!ELEMENT A EMPTY>
<!ATTLIST A
    ID CDATA #IMPLIED
    NAME CDATA #REQUIRED
>

<!ELEMENT B EMPTY>
<!ATTLIST B
    ID CDATA #IMPLIED
    NAME CDATA #REQUIRED
    A_ID CDATA #REQUIRED
>

<!ELEMENT C EMPTY>
<!ATTLIST C
    ID CDATA #IMPLIED
    NAME CDATA #REQUIRED
    B_ID CDATA #REQUIRED
>

<!ELEMENT ITEM EMPTY>
<!ATTLIST ITEM
    ID CDATA #IMPLIED
    COUNT CDATA #REQUIRED
    DATE CDATA #REQUIRED
    NAME CDATA #REQUIRED
>

=== jrybak23/jpa-loading-strategies/src/test/resources/datasets/dataset2.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "schema.dtd">
<dataset>
    <A ID="1" NAME="a1"/>
    <A ID="2" NAME="a2"/>

    <B ID="1" NAME="b1" A_ID="1"/>
    <B ID="2" NAME="b2" A_ID="1"/>
    <B ID="3" NAME="b3" A_ID="2"/>

    <C ID="1" NAME="c1" B_ID="1"/>
    <C ID="2" NAME="c2" B_ID="1"/>
    <C ID="3" NAME="c3" B_ID="2"/>
</dataset>
